# Nome do workflow do GitHub Actions
name: Teste CIDSSAT 
 
# Evento que desencadeia o workflow
on:
   push:
    branches:
      - circleci-project-setup
    # Definir um trabalho (job) dentro do workflow
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up ARM64 emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      - name: Run Docker container
        run: docker run --platform linux/arm64/v8 thiagoferreira53/ci-dssat-csm-os:latest
        
