# Nome do workflow do GitHub Actions
name: Teste CIDSSAT 

# Evento que desencadeia o workflow
on:
   push:
    branches:
      - circleci-project-setup
    # Definir um trabalho (job) dentro do workflow
jobs:
  say-hello:
    # Definir o ambiente de execução do job
    runs-on: ubuntu-latest
    # Definir os passos do job
    steps:
      # Fazer o checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar o Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Executar o container Docker com a imagem especificada
      - name: Run Docker container
        run: |
          docker run --rm --name say-hello-container thiagoferreira53/ci-dssat-csm-os:latest /bin/bash -c "echo Hello, World!"
