name: CI Build e Run DSSAT-CSM test
  
on:
  push:
    branches:
      - develop

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y git ca-certificates gfortran cmake

      - name: Clone Repositories
        run: |
          git clone -b develop https://github.com/DSSAT/ci-dssat-csm-os.git
          git clone -b develop https://github.com/DSSAT/dssat-csm-data.git

      - name: DSSAT data directory
        run: |
          mkdir -p /Applications/DSSAT48/
          mkdir -p /Applications/DSSAT48/CTWork/workA
          mkdir -p /Applications/DSSAT48/CTWork/workB
          cp -r dssat-csm-data/* /Applications/DSSAT48/
          
      - name: Compile
        run: |
          mkdir -p ci-dssat-csm-os/build
          cd ci-dssat-csm-os/build
          cmake -DCMAKE_INSTALL_PREFIX=/Applications/DSSAT48/ ..
          make install

      - name: Copy executable
        run: |
          cp ci-dssat-csm-os/build/bin/dscsm048 /Applications/DSSAT48/CTWork/workA/
          cp ci-dssat-csm-os/build/bin/dscsm048 /Applications/DSSAT48/CTWork/workB/

      - name: Run workA
        run: |
          cd /Applications/DSSAT48/CTWork/workA
          ./dscsm048 B ../../BatchFiles/All.L48

      - name: Run workB
        run: |
          cd /Applications/DSSAT48/CTWork/workB
          ./dscsm048 B ../../BatchFiles/All.L48


      - name: CropTest
        run: |
          #PUT HERE THE CROPTEST LOGIC TO COMPARE FILES.

