name: CI Build e Run DSSAT-CSM test
   
on:
  push:
    branches:
      - make-CropTest-WORK

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
       R_LIBS_USER: ~/R/library
       
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y git ca-certificates gfortran cmake

      - name: Clone Repositories
        run: |
          git clone -b develop https://github.com/DSSAT/ci-dssat-csm-os.git
          git clone -b develop https://github.com/DSSAT/dssat-csm-data.git

      - name: DSSAT data directory
        run: |
          sudo mkdir -p /Applications/DSSAT48/
          sudo mkdir -p /Applications/DSSAT48/CTWork/workA
          sudo mkdir -p /Applications/DSSAT48/CTWork/workB
          sudo chmod -R 777 /Applications/DSSAT48/
          cp -r dssat-csm-data/* /Applications/DSSAT48/
          
      - name: Compile
        run: |
          mkdir -p ci-dssat-csm-os/build
          cd ci-dssat-csm-os/build
          cmake -DCMAKE_INSTALL_PREFIX=/Applications/DSSAT48/ ..
          sudo make install

      - name: Copy executable
        run: |
          cp ci-dssat-csm-os/build/bin/dscsm048 /Applications/DSSAT48/CTWork/workA/
          cp ci-dssat-csm-os/build/bin/dscsm048 /Applications/DSSAT48/CTWork/workB/

      - name: Run workA
        run: |
          export DSSAT_HOME="/Applications/DSSAT48/"
          cd /Applications/DSSAT48/CTWork/workA
          ./dscsm048 B ../../BatchFiles/All.L48

      - name: Run workB
        run: |
          export DSSAT_HOME="/Applications/DSSAT48/"
          cd /Applications/DSSAT48/CTWork/workB
          ./dscsm048 B ../../BatchFiles/All.L48

 #        PUT HERE THE CROPTEST LOGIC TO COMPARE FILES.
 #     - name: CropTest
 #       run: |
 #        cd /Applications/DSSAT48/CTWork/
 #        diff -i workA/Summary.OUT workB/Summary.OUT

      - name: Configura o ambiente R 
        uses: r-lib/actions/setup-r@v2
           
      - name: Install package
        run: |
          Rscript -e "install.packages('devtools', dependencies = TRUE)"
          Rscript -e "install.packages(c('plumber', 'webutils', 'sodium'))"
           
      - name: Verify installation
        run: |
           Rscript -e "print('Installed packages:'); print(installed.packages())"
       
      - name: Run RCroptest
        run: |
          export DSSAT_HOME="/Applications/DSSAT48/"
          cd /Applications/DSSAT48/CTWork/
          Rscript -e "library(devtools);
              devtools::load_all('.github/RCroptest');
              result = testCI('/Applications/DSSAT48/CTWork/workA/Summary.out',
                              '/Applications/DSSAT48/CTWork/workB/Summary.out', 
                              thNumeric=2, thDate=0
                             );
              print(paste("The valor of the result is:", result))

           if (result == 0) {
             print("There are NO differences between the models.")
           } else {
             stop('There are differences between the models')
           }"
